-- The three DB webhook triggers (status-submitted email, issue-blocks-
-- completion revisit, issue-Monday sync — 20260109000000, 20260112000000,
-- 20260113000000) all call net.http_post(), on the assumption that pg_net
-- is already enabled. That's true of the Supabase CLI's local dev stack
-- by default, but NOT of a real hosted Supabase Cloud project — nothing
-- ever actually enabled it there. Unlike a missing app_settings row
-- (which those triggers no-op on gracefully), a missing schema is a hard
-- error that rolls back the entire statement that fired the trigger — so
-- production was left with "raising an issue" failing outright, not just
-- silently not syncing.
--
-- No `with schema net` clause: that requires the target schema to already
-- exist *before* CREATE EXTENSION runs, which defeats the point on a
-- fresh database — pg_net's own control file already fixes its schema to
-- `net` and creates that schema itself as part of installation.
create extension if not exists pg_net;
